### ISSUE TITLE
Update config-domain CM for the routes to work.

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift-cloud-functions/Documentation#25]
The step should here
https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP-4x.md#post-installation-tasks

should include

editing the configmap `config-domain` in the `knative-serving` project to replace `example.com` with your domain name.

```
oc edit configmap config-domain -n knative-serving
```

**Comment by bbrowning** [comment]
We'll be doing that automatically on behalf of the user soon - see https://github.com/openshift-knative/knative-serving-operator/blob/fe03781bfd0beb9f2df07993c743d5329b890852/pkg/controller/install/install_controller.go#L240

**Comment by abrennan89** [comment]
Closing this issue since the process will be automated.
