### ISSUE TITLE
minishift doc refers to prep-knative.sh script

### ISSUE THREAD

**Issue by jsanda** [openshift-cloud-functions/Documentation#7]
There is a section in the minishift doc that mentions running `etc/scripts/prep-knative.sh`. I assume that is referring to the `etc/scripts` directory in the knative-operators repo. That file does not exist.

**Comment by abrennan89** [comment]
Resolved in latest commit; https://github.com/openshift-cloud-functions/Documentation/commit/25abadffdcc61d6672a159993448f19bc849b5d2
